# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/joao/nogueira/iCubSimulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/joao/nogueira/iCubSimulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joao/nogueira/iCubSimulator/CMakeFiles /home/joao/nogueira/iCubSimulator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joao/nogueira/iCubSimulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named myDemo

# Build rule for target.
myDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 myDemo
.PHONY : myDemo

# fast build rule for target.
myDemo/fast:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/build
.PHONY : myDemo/fast

# target to build an object file
iCubSimulator.o:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/iCubSimulator.o
.PHONY : iCubSimulator.o

# target to preprocess a source file
iCubSimulator.i:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/iCubSimulator.i
.PHONY : iCubSimulator.i

# target to generate assembly for a file
iCubSimulator.s:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/iCubSimulator.s
.PHONY : iCubSimulator.s

# target to build an object file
include/moc_Window.o:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/include/moc_Window.o
.PHONY : include/moc_Window.o

# target to preprocess a source file
include/moc_Window.i:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/include/moc_Window.i
.PHONY : include/moc_Window.i

# target to generate assembly for a file
include/moc_Window.s:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/include/moc_Window.s
.PHONY : include/moc_Window.s

# target to build an object file
src/ApproachMovementSpace.o:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/ApproachMovementSpace.o
.PHONY : src/ApproachMovementSpace.o

# target to preprocess a source file
src/ApproachMovementSpace.i:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/ApproachMovementSpace.i
.PHONY : src/ApproachMovementSpace.i

# target to generate assembly for a file
src/ApproachMovementSpace.s:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/ApproachMovementSpace.s
.PHONY : src/ApproachMovementSpace.s

# target to build an object file
src/LogManager.o:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/LogManager.o
.PHONY : src/LogManager.o

# target to preprocess a source file
src/LogManager.i:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/LogManager.i
.PHONY : src/LogManager.i

# target to generate assembly for a file
src/LogManager.s:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/LogManager.s
.PHONY : src/LogManager.s

# target to build an object file
src/OptFuncs.o:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/OptFuncs.o
.PHONY : src/OptFuncs.o

# target to preprocess a source file
src/OptFuncs.i:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/OptFuncs.i
.PHONY : src/OptFuncs.i

# target to generate assembly for a file
src/OptFuncs.s:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/OptFuncs.s
.PHONY : src/OptFuncs.s

# target to build an object file
src/OrientedBoundingBox.o:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/OrientedBoundingBox.o
.PHONY : src/OrientedBoundingBox.o

# target to preprocess a source file
src/OrientedBoundingBox.i:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/OrientedBoundingBox.i
.PHONY : src/OrientedBoundingBox.i

# target to generate assembly for a file
src/OrientedBoundingBox.s:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/OrientedBoundingBox.s
.PHONY : src/OrientedBoundingBox.s

# target to build an object file
src/RKHS.o:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/RKHS.o
.PHONY : src/RKHS.o

# target to preprocess a source file
src/RKHS.i:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/RKHS.i
.PHONY : src/RKHS.i

# target to generate assembly for a file
src/RKHS.s:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/RKHS.s
.PHONY : src/RKHS.s

# target to build an object file
src/TGPOptimization.o:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/TGPOptimization.o
.PHONY : src/TGPOptimization.o

# target to preprocess a source file
src/TGPOptimization.i:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/TGPOptimization.i
.PHONY : src/TGPOptimization.i

# target to generate assembly for a file
src/TGPOptimization.s:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/TGPOptimization.s
.PHONY : src/TGPOptimization.s

# target to build an object file
src/Window.o:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/Window.o
.PHONY : src/Window.o

# target to preprocess a source file
src/Window.i:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/Window.i
.PHONY : src/Window.i

# target to generate assembly for a file
src/Window.s:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/Window.s
.PHONY : src/Window.s

# target to build an object file
src/iCub.o:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/iCub.o
.PHONY : src/iCub.o

# target to preprocess a source file
src/iCub.i:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/iCub.i
.PHONY : src/iCub.i

# target to generate assembly for a file
src/iCub.s:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/iCub.s
.PHONY : src/iCub.s

# target to build an object file
src/iCubHand.o:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/iCubHand.o
.PHONY : src/iCubHand.o

# target to preprocess a source file
src/iCubHand.i:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/iCubHand.i
.PHONY : src/iCubHand.i

# target to generate assembly for a file
src/iCubHand.s:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/iCubHand.s
.PHONY : src/iCubHand.s

# target to build an object file
src/iCubOptimizable.o:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/iCubOptimizable.o
.PHONY : src/iCubOptimizable.o

# target to preprocess a source file
src/iCubOptimizable.i:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/iCubOptimizable.i
.PHONY : src/iCubOptimizable.i

# target to generate assembly for a file
src/iCubOptimizable.s:
	$(MAKE) -f CMakeFiles/myDemo.dir/build.make CMakeFiles/myDemo.dir/src/iCubOptimizable.s
.PHONY : src/iCubOptimizable.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... myDemo"
	@echo "... rebuild_cache"
	@echo "... iCubSimulator.o"
	@echo "... iCubSimulator.i"
	@echo "... iCubSimulator.s"
	@echo "... include/moc_Window.o"
	@echo "... include/moc_Window.i"
	@echo "... include/moc_Window.s"
	@echo "... src/ApproachMovementSpace.o"
	@echo "... src/ApproachMovementSpace.i"
	@echo "... src/ApproachMovementSpace.s"
	@echo "... src/LogManager.o"
	@echo "... src/LogManager.i"
	@echo "... src/LogManager.s"
	@echo "... src/OptFuncs.o"
	@echo "... src/OptFuncs.i"
	@echo "... src/OptFuncs.s"
	@echo "... src/OrientedBoundingBox.o"
	@echo "... src/OrientedBoundingBox.i"
	@echo "... src/OrientedBoundingBox.s"
	@echo "... src/RKHS.o"
	@echo "... src/RKHS.i"
	@echo "... src/RKHS.s"
	@echo "... src/TGPOptimization.o"
	@echo "... src/TGPOptimization.i"
	@echo "... src/TGPOptimization.s"
	@echo "... src/Window.o"
	@echo "... src/Window.i"
	@echo "... src/Window.s"
	@echo "... src/iCub.o"
	@echo "... src/iCub.i"
	@echo "... src/iCub.s"
	@echo "... src/iCubHand.o"
	@echo "... src/iCubHand.i"
	@echo "... src/iCubHand.s"
	@echo "... src/iCubOptimizable.o"
	@echo "... src/iCubOptimizable.i"
	@echo "... src/iCubOptimizable.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

